// ========================================
// SISTEMA DE VASCO DE CONVERSAS
// ========================================

// Configurações gerais
const CONVERSATION_CONFIG = {
    duration: 7 * 60 * 60 * 1000, // 7 horas em milissegundos
    minInterval: 60000, // 1 minuto mínimo
    maxInterval: 600000, // 10 minutos máximo
    messagesPerHour: 20, // ~20 mensagens por hora
    totalMessages: 140 // Total de mensagens para 7 horas
};

// ========================================
// VASCO DE CONVERSAS - NEGÓCIOS/VENDAS
// ========================================
const BUSINESS_CONVERSATIONS = {
    name: "Negócios/Vendas",
    icon: "🏢",
    color: "#2196F3",
    messages: [
        // Saudações iniciais
        "Oi! Como você está?",
        "Olá! Tudo bem?",
        "Oi! Como vai?",
        "Olá! Como está?",
        "Oi! Tudo certo?",
        "Olá! Como você está?",
        "Oi! Tudo bem por aí?",
        "Olá! Como vai?",
        
        // Perguntas sobre trabalho
        "Você trabalha com vendas?",
        "Qual sua área de atuação?",
        "Como funciona seu negócio?",
        "Você tem algum produto?",
        "Qual seu produto principal?",
        "Como você vende?",
        "Tem alguma promoção?",
        "Qual seu nicho?",
        "Como você trabalha?",
        "Qual sua especialidade?",
        
        // Conversas sobre produtos
        "Tem algum produto interessante?",
        "Qual produto vende mais?",
        "Como são seus produtos?",
        "Tem algum serviço?",
        "Qual seu serviço principal?",
        "Como funciona seu produto?",
        "Tem algum curso?",
        "Qual seu melhor produto?",
        "Como você cria seus produtos?",
        "Tem alguma novidade?",
        
        // Perguntas sobre clientes
        "Como você encontra clientes?",
        "Qual seu público-alvo?",
        "Como você atrai clientes?",
        "Qual sua estratégia?",
        "Como você vende online?",
        "Tem muitos clientes?",
        "Como você fideliza?",
        "Qual sua taxa de conversão?",
        "Como você prospecta?",
        "Qual seu método?",
        
        // Conversas sobre resultados
        "Como estão suas vendas?",
        "Qual seu faturamento?",
        "Como você mede sucesso?",
        "Qual seu objetivo?",
        "Como você cresce?",
        "Qual sua meta?",
        "Como você escala?",
        "Qual seu plano?",
        "Como você inova?",
        "Qual sua visão?",
        
        // Perguntas sobre mercado
        "Como está o mercado?",
        "Qual a concorrência?",
        "Como você se diferencia?",
        "Qual sua vantagem?",
        "Como você compete?",
        "Qual sua estratégia?",
        "Como você se posiciona?",
        "Qual seu diferencial?",
        "Como você se destaca?",
        "Qual sua proposta?",
        
        // Conversas sobre tecnologia
        "Você usa tecnologia?",
        "Como você automatiza?",
        "Qual ferramenta usa?",
        "Como você otimiza?",
        "Qual plataforma usa?",
        "Como você digitaliza?",
        "Qual sistema usa?",
        "Como você integra?",
        "Qual app prefere?",
        "Como você conecta?",
        
        // Perguntas sobre parcerias
        "Você faz parcerias?",
        "Como você colabora?",
        "Qual sua rede?",
        "Como você conecta?",
        "Você tem sócios?",
        "Como você trabalha em equipe?",
        "Qual sua comunidade?",
        "Como você networking?",
        "Você tem mentores?",
        "Como você aprende?",
        
        // Conversas sobre futuro
        "Qual seu próximo passo?",
        "Como você planeja?",
        "Qual sua meta?",
        "Como você evolui?",
        "Qual seu sonho?",
        "Como você cresce?",
        "Qual sua visão?",
        "Como você inova?",
        "Qual seu objetivo?",
        "Como você transforma?",
        
        // Perguntas sobre desafios
        "Qual seu maior desafio?",
        "Como você supera?",
        "Qual sua dificuldade?",
        "Como você resolve?",
        "Qual seu obstáculo?",
        "Como você enfrenta?",
        "Qual sua barreira?",
        "Como você vence?",
        "Qual seu problema?",
        "Como você soluciona?",
        
        // Conversas finais
        "Foi ótimo conversar!",
        "Obrigado pela conversa!",
        "Até a próxima!",
        "Foi um prazer!",
        "Conversa muito boa!",
        "Obrigado pelo papo!",
        "Até logo!",
        "Foi interessante!",
        "Obrigado pela troca!",
        "Até mais!"
    ],
    responses: [
        "Estou bem, obrigado! E você?",
        "Tudo certo! Como você está?",
        "Vou bem! E aí?",
        "Tudo bem! Como vai?",
        "Estou ótimo! E você?",
        "Vou muito bem! Como está?",
        "Tudo certo! E aí?",
        "Estou bem! Como você está?",
        "Vou bem! E como vai?",
        "Tudo ótimo! E você?",
        "Sim, trabalho com vendas!",
        "Trabalho com produtos digitais!",
        "Minha área é marketing!",
        "Trabalho com serviços!",
        "Minha especialidade é vendas!",
        "Trabalho com e-commerce!",
        "Minha área é consultoria!",
        "Trabalho com afiliados!",
        "Minha especialidade é digital!",
        "Trabalho com infoprodutos!",
        "Tenho vários produtos!",
        "Meu produto principal é curso!",
        "Vendo produtos digitais!",
        "Tenho serviços de consultoria!",
        "Meu produto é software!",
        "Vendo e-books!",
        "Tenho cursos online!",
        "Meu produto é app!",
        "Vendo templates!",
        "Tenho ferramentas!",
        "Uso redes sociais!",
        "Meu público é empreendedores!",
        "Atraio com conteúdo!",
        "Minha estratégia é inbound!",
        "Vendo pelo Instagram!",
        "Tenho muitos clientes!",
        "Fidelizo com qualidade!",
        "Minha taxa é boa!",
        "Prospecto pelo LinkedIn!",
        "Meu método é consultivo!",
        "As vendas estão ótimas!",
        "Meu faturamento cresce!",
        "Medo pelo ROI!",
        "Meu objetivo é crescer!",
        "Cresço com inovação!",
        "Minha meta é escalar!",
        "Escalo com automação!",
        "Meu plano é expandir!",
        "Inovo constantemente!",
        "Minha visão é transformar!",
        "O mercado está aquecido!",
        "A concorrência é forte!",
        "Me diferencio pela qualidade!",
        "Minha vantagem é preço!",
        "Competo com inovação!",
        "Minha estratégia é nicho!",
        "Me posiciono como especialista!",
        "Meu diferencial é atendimento!",
        "Me destaco pela experiência!",
        "Minha proposta é valor!",
        "Uso muita tecnologia!",
        "Automatizo processos!",
        "Uso várias ferramentas!",
        "Otimizo constantemente!",
        "Uso plataformas modernas!",
        "Digitalizo tudo!",
        "Uso sistemas integrados!",
        "Integro várias soluções!",
        "Prefiro apps móveis!",
        "Conecto tudo!",
        "Faço muitas parcerias!",
        "Colaboro sempre!",
        "Tenho uma rede forte!",
        "Conecto pessoas!",
        "Tenho sócios estratégicos!",
        "Trabalho em equipe!",
        "Minha comunidade é grande!",
        "Faço muito networking!",
        "Tenho mentores incríveis!",
        "Aprendo sempre!",
        "Meu próximo passo é expandir!",
        "Planejo crescer mais!",
        "Minha meta é internacional!",
        "Evoluo constantemente!",
        "Meu sonho é impactar!",
        "Cresço todos os dias!",
        "Minha visão é global!",
        "Inovo sempre!",
        "Meu objetivo é liderar!",
        "Transformo mercados!",
        "Meu maior desafio é tempo!",
        "Supero com foco!",
        "Minha dificuldade é escala!",
        "Resolvo com tecnologia!",
        "Meu obstáculo é recursos!",
        "Enfrento com estratégia!",
        "Minha barreira é conhecimento!",
        "Venço com persistência!",
        "Meu problema é gestão!",
        "Soluciono com processos!",
        "Foi ótimo mesmo!",
        "Obrigado você também!",
        "Até a próxima!",
        "Foi um prazer!",
        "Conversa excelente!",
        "Obrigado pelo papo!",
        "Até logo!",
        "Foi muito interessante!",
        "Obrigado pela troca!",
        "Até mais!"
    ]
};

// ========================================
// VASCO DE CONVERSAS - SOCIAL/AMIGOS
// ========================================
const SOCIAL_CONVERSATIONS = {
    name: "Social/Amigos",
    icon: "👥",
    color: "#4CAF50",
    messages: [
        // Saudações casuais
        "Oi! Como você está?",
        "Olá! Tudo bem?",
        "Oi! Como vai?",
        "Olá! Como está?",
        "Oi! Tudo certo?",
        "Olá! Como você está?",
        "Oi! Tudo bem por aí?",
        "Olá! Como vai?",
        "Oi! E aí?",
        "Olá! Como está?",
        
        // Perguntas sobre o dia
        "Como foi seu dia?",
        "O que você fez hoje?",
        "Como está seu dia?",
        "O que você está fazendo?",
        "Como foi sua manhã?",
        "O que você fez ontem?",
        "Como está sua semana?",
        "O que você planeja?",
        "Como foi seu fim de semana?",
        "O que você gosta de fazer?",
        
        // Conversas sobre família
        "Como está a família?",
        "Como estão os filhos?",
        "Como está sua mãe?",
        "Como está seu pai?",
        "Como estão os irmãos?",
        "Como está sua esposa?",
        "Como está seu marido?",
        "Como estão os avós?",
        "Como está todo mundo?",
        "Como está a casa?",
        
        // Perguntas sobre trabalho
        "Como está o trabalho?",
        "O que você faz?",
        "Como está sua empresa?",
        "O que você trabalha?",
        "Como está sua carreira?",
        "O que você estuda?",
        "Como está a faculdade?",
        "O que você aprende?",
        "Como está seu curso?",
        "O que você desenvolve?",
        
        // Conversas sobre hobbies
        "O que você gosta de fazer?",
        "Qual seu hobby?",
        "O que você faz no tempo livre?",
        "Qual seu esporte favorito?",
        "O que você assiste?",
        "Qual sua série favorita?",
        "O que você lê?",
        "Qual seu livro favorito?",
        "O que você escuta?",
        "Qual sua música favorita?",
        
        // Perguntas sobre viagens
        "Você viaja muito?",
        "Para onde você vai?",
        "Qual seu destino favorito?",
        "O que você conhece?",
        "Para onde você quer ir?",
        "Qual sua viagem dos sonhos?",
        "O que você explora?",
        "Qual lugar você ama?",
        "Para onde você volta?",
        "O que você descobre?",
        
        // Conversas sobre comida
        "O que você come?",
        "Qual sua comida favorita?",
        "O que você cozinha?",
        "Qual seu restaurante favorito?",
        "O que você experimenta?",
        "Qual sua receita?",
        "O que você gosta?",
        "Qual seu prato favorito?",
        "O que você saboreia?",
        "Qual sua especialidade?",
        
        // Perguntas sobre saúde
        "Como está sua saúde?",
        "Você se exercita?",
        "Como você cuida?",
        "O que você faz?",
        "Como você se sente?",
        "Você medita?",
        "Como você relaxa?",
        "O que você pratica?",
        "Como você equilibra?",
        "O que você prioriza?",
        
        // Conversas sobre sonhos
        "Qual seu sonho?",
        "O que você quer?",
        "Qual sua meta?",
        "O que você planeja?",
        "Qual sua visão?",
        "O que você busca?",
        "Qual seu objetivo?",
        "O que você almeja?",
        "Qual sua aspiração?",
        "O que você deseja?",
        
        // Perguntas sobre futuro
        "O que você planeja?",
        "Qual seu próximo passo?",
        "O que você quer fazer?",
        "Como você vê?",
        "O que você espera?",
        "Qual sua expectativa?",
        "O que você imagina?",
        "Como você sonha?",
        "O que você projeta?",
        "Qual sua perspectiva?",
        
        // Conversas finais
        "Foi ótimo conversar!",
        "Obrigado pela conversa!",
        "Até a próxima!",
        "Foi um prazer!",
        "Conversa muito boa!",
        "Obrigado pelo papo!",
        "Até logo!",
        "Foi interessante!",
        "Obrigado pela troca!",
        "Até mais!"
    ],
    responses: [
        "Estou bem, obrigado! E você?",
        "Tudo certo! Como você está?",
        "Vou bem! E aí?",
        "Tudo bem! Como vai?",
        "Estou ótimo! E você?",
        "Vou muito bem! Como está?",
        "Tudo certo! E aí?",
        "Estou bem! Como você está?",
        "Vou bem! E como vai?",
        "Tudo ótimo! E você?",
        "Meu dia foi ótimo!",
        "Fiz várias coisas!",
        "Meu dia está bom!",
        "Estou trabalhando!",
        "Minha manhã foi produtiva!",
        "Ontem foi tranquilo!",
        "Minha semana está corrida!",
        "Planejo descansar!",
        "Meu fim de semana foi relaxante!",
        "Gosto de ler e viajar!",
        "A família está bem!",
        "Os filhos estão ótimos!",
        "Minha mãe está bem!",
        "Meu pai está ótimo!",
        "Os irmãos estão bem!",
        "Minha esposa está ótima!",
        "Meu marido está bem!",
        "Os avós estão ótimos!",
        "Todo mundo está bem!",
        "A casa está organizada!",
        "O trabalho está bom!",
        "Trabalho com tecnologia!",
        "Minha empresa está crescendo!",
        "Trabalho com vendas!",
        "Minha carreira está evoluindo!",
        "Estudo marketing!",
        "A faculdade está ótima!",
        "Aprendo muito!",
        "Meu curso está interessante!",
        "Desenvolvo projetos!",
        "Gosto de ler e cozinhar!",
        "Meu hobby é fotografia!",
        "No tempo livre viajo!",
        "Meu esporte favorito é futebol!",
        "Assisto séries!",
        "Minha série favorita é Stranger Things!",
        "Leio muito!",
        "Meu livro favorito é O Poder do Hábito!",
        "Escuto música!",
        "Minha música favorita é MPB!",
        "Viajo sempre que posso!",
        "Vou para a praia!",
        "Meu destino favorito é Europa!",
        "Conheço vários lugares!",
        "Quero ir para o Japão!",
        "Minha viagem dos sonhos é volta ao mundo!",
        "Exploro cidades!",
        "Amo a natureza!",
        "Volto sempre para casa!",
        "Descubro lugares novos!",
        "Como de tudo!",
        "Minha comida favorita é italiana!",
        "Cozinho bem!",
        "Meu restaurante favorito é japonês!",
        "Experimentei comida tailandesa!",
        "Minha receita é lasanha!",
        "Gosto de frutos do mar!",
        "Meu prato favorito é sushi!",
        "Saboreio vinhos!",
        "Minha especialidade é sobremesas!",
        "Minha saúde está ótima!",
        "Me exercito regularmente!",
        "Cuido da alimentação!",
        "Faço caminhadas!",
        "Me sinto muito bem!",
        "Medito todos os dias!",
        "Relaxo lendo!",
        "Pratico yoga!",
        "Equilibro trabalho e vida!",
        "Priorizo minha saúde!",
        "Meu sonho é viajar o mundo!",
        "Quero ser feliz!",
        "Minha meta é crescer!",
        "Planejo estudar mais!",
        "Minha visão é positiva!",
        "Busco conhecimento!",
        "Meu objetivo é ajudar!",
        "Almejo sucesso!",
        "Minha aspiração é impactar!",
        "Desejo paz!",
        "Planejo viajar mais!",
        "Meu próximo passo é estudar!",
        "Quero fazer um curso!",
        "Vejo um futuro brilhante!",
        "Espero coisas boas!",
        "Minha expectativa é alta!",
        "Imagino muitas possibilidades!",
        "Sonho com viagens!",
        "Projeto uma carreira sólida!",
        "Minha perspectiva é otimista!",
        "Foi ótimo mesmo!",
        "Obrigado você também!",
        "Até a próxima!",
        "Foi um prazer!",
        "Conversa excelente!",
        "Obrigado pelo papo!",
        "Até logo!",
        "Foi muito interessante!",
        "Obrigado pela troca!",
        "Até mais!"
    ]
};

// ========================================
// VASCO DE CONVERSAS - CLIENTES/PRODUTOS
// ========================================
const CUSTOMER_CONVERSATIONS = {
    name: "Clientes/Produtos",
    icon: "🛒",
    color: "#FF9800",
    messages: [
        // Saudações comerciais
        "Olá! Como posso ajudar?",
        "Oi! Precisa de alguma coisa?",
        "Olá! Como posso ser útil?",
        "Oi! Tem alguma dúvida?",
        "Olá! Precisa de informações?",
        "Oi! Como posso assistir?",
        "Olá! Tem alguma pergunta?",
        "Oi! Precisa de suporte?",
        "Olá! Como posso resolver?",
        "Oi! Tem alguma necessidade?",
        
        // Perguntas sobre produtos
        "Qual produto você procura?",
        "O que você precisa?",
        "Qual seu interesse?",
        "O que você busca?",
        "Qual sua necessidade?",
        "O que você quer?",
        "Qual produto te interessa?",
        "O que você procura?",
        "Qual sua preferência?",
        "O que você gosta?",
        
        // Conversas sobre características
        "Qual tamanho você quer?",
        "Que cor você prefere?",
        "Qual modelo você gosta?",
        "Que tipo você busca?",
        "Qual versão você quer?",
        "Que estilo você prefere?",
        "Qual marca você gosta?",
        "Que qualidade você quer?",
        "Qual preço você busca?",
        "Que benefício você quer?",
        
        // Perguntas sobre uso
        "Para que você vai usar?",
        "Como você vai usar?",
        "Onde você vai usar?",
        "Quando você vai usar?",
        "Por que você precisa?",
        "Quem vai usar?",
        "Qual seu objetivo?",
        "Como você pretende?",
        "Qual sua aplicação?",
        "Como você planeja?",
        
        // Conversas sobre preço
        "Qual seu orçamento?",
        "Quanto você quer gastar?",
        "Qual seu limite?",
        "Que preço você busca?",
        "Qual sua faixa?",
        "Quanto você tem?",
        "Qual seu investimento?",
        "Que valor você pensa?",
        "Qual sua expectativa?",
        "Quanto você pode?",
        
        // Perguntas sobre entrega
        "Quando você precisa?",
        "Qual sua urgência?",
        "Quando você quer?",
        "Qual seu prazo?",
        "Quando você recebe?",
        "Qual sua data?",
        "Quando você espera?",
        "Qual sua necessidade?",
        "Quando você planeja?",
        "Qual sua expectativa?",
        
        // Conversas sobre garantia
        "Você quer garantia?",
        "Qual garantia você quer?",
        "Que tipo de garantia?",
        "Qual sua preferência?",
        "Que segurança você quer?",
        "Qual proteção você busca?",
        "Que tranquilidade você quer?",
        "Qual sua necessidade?",
        "Que confiança você quer?",
        "Qual sua expectativa?",
        
        // Perguntas sobre pagamento
        "Como você quer pagar?",
        "Qual forma de pagamento?",
        "Que método você prefere?",
        "Como você paga?",
        "Qual sua preferência?",
        "Que opção você quer?",
        "Como você prefere?",
        "Qual sua escolha?",
        "Que forma você usa?",
        "Como você faz?",
        
        // Conversas sobre desconto
        "Você quer desconto?",
        "Qual desconto você quer?",
        "Que promoção você busca?",
        "Qual oferta você quer?",
        "Que benefício você quer?",
        "Qual vantagem você busca?",
        "Que economia você quer?",
        "Qual redução você quer?",
        "Que valor você quer?",
        "Qual preço você quer?",
        
        // Perguntas finais
        "Alguma outra dúvida?",
        "Mais alguma coisa?",
        "Outra pergunta?",
        "Mais informações?",
        "Outra necessidade?",
        "Mais alguma coisa?",
        "Outra dúvida?",
        "Mais alguma pergunta?",
        "Outra questão?",
        "Mais alguma informação?",
        
        // Conversas finais
        "Foi um prazer ajudar!",
        "Obrigado pela preferência!",
        "Até a próxima!",
        "Foi ótimo atendê-lo!",
        "Conversa muito boa!",
        "Obrigado pelo contato!",
        "Até logo!",
        "Foi interessante!",
        "Obrigado pela confiança!",
        "Até mais!"
    ],
    responses: [
        "Preciso de informações!",
        "Tenho algumas dúvidas!",
        "Quero saber mais!",
        "Preciso de ajuda!",
        "Tenho perguntas!",
        "Quero entender melhor!",
        "Preciso de orientação!",
        "Tenho interesse!",
        "Quero conhecer!",
        "Preciso de suporte!",
        "Procuro um produto específico!",
        "Preciso de algo especial!",
        "Tenho interesse em vários!",
        "Quero conhecer as opções!",
        "Preciso de algo prático!",
        "Tenho uma necessidade específica!",
        "Quero algo de qualidade!",
        "Preciso de algo durável!",
        "Tenho interesse em novidades!",
        "Quero algo moderno!",
        "Quero tamanho médio!",
        "Prefiro azul!",
        "Gosto do modelo novo!",
        "Busco algo clássico!",
        "Quero a versão completa!",
        "Prefiro estilo moderno!",
        "Gosto de marcas conhecidas!",
        "Quero alta qualidade!",
        "Busco bom custo-benefício!",
        "Quero algo prático!",
        "Vou usar no trabalho!",
        "Vou usar em casa!",
        "Vou usar todos os dias!",
        "Vou usar em viagens!",
        "Preciso para um projeto!",
        "Vou usar com a família!",
        "Preciso para estudar!",
        "Vou usar profissionalmente!",
        "Preciso para lazer!",
        "Vou usar regularmente!",
        "Meu orçamento é flexível!",
        "Quero gastar até R$ 500!",
        "Meu limite é R$ 1000!",
        "Busco algo em conta!",
        "Minha faixa é média!",
        "Tenho R$ 300!",
        "Meu investimento é R$ 800!",
        "Penso em R$ 200!",
        "Minha expectativa é boa!",
        "Posso até R$ 600!",
        "Preciso para esta semana!",
        "Minha urgência é média!",
        "Quero para hoje!",
        "Meu prazo é flexível!",
        "Quero receber rápido!",
        "Minha data é próxima semana!",
        "Espero para o mês que vem!",
        "Minha necessidade é urgente!",
        "Planejo para o próximo mês!",
        "Minha expectativa é breve!",
        "Quero garantia de 1 ano!",
        "Preciso de garantia estendida!",
        "Quero garantia completa!",
        "Prefiro garantia longa!",
        "Quero segurança total!",
        "Busco proteção máxima!",
        "Quero tranquilidade!",
        "Preciso de confiança!",
        "Quero garantia sólida!",
        "Minha expectativa é alta!",
        "Quero pagar à vista!",
        "Prefiro cartão!",
        "Quero parcelar!",
        "Prefiro PIX!",
        "Quero boleto!",
        "Prefiro débito!",
        "Quero crédito!",
        "Prefiro transferência!",
        "Quero dinheiro!",
        "Prefiro online!",
        "Quero desconto de 10%!",
        "Busco promoção!",
        "Quero oferta especial!",
        "Preciso de benefício!",
        "Quero vantagem!",
        "Busco economia!",
        "Quero redução!",
        "Preciso de valor menor!",
        "Quero preço melhor!",
        "Não, obrigado!",
        "Está tudo certo!",
        "Não tenho mais dúvidas!",
        "Já tenho todas as informações!",
        "Não preciso de mais nada!",
        "Está perfeito!",
        "Não tenho outras perguntas!",
        "Já esclareci tudo!",
        "Não tenho mais questões!",
        "Já tenho todas as informações!",
        "Foi ótimo mesmo!",
        "Obrigado pelo atendimento!",
        "Até a próxima!",
        "Foi um prazer!",
        "Conversa excelente!",
        "Obrigado pela ajuda!",
        "Até logo!",
        "Foi muito interessante!",
        "Obrigado pela paciência!",
        "Até mais!"
    ]
};

// ========================================
// VASCO DE CONVERSAS - SUPORTE/ATENDIMENTO
// ========================================
const SUPPORT_CONVERSATIONS = {
    name: "Suporte/Atendimento",
    icon: "📞",
    color: "#9C27B0",
    messages: [
        // Saudações de suporte
        "Olá! Como posso ajudar?",
        "Oi! Precisa de suporte?",
        "Olá! Tem alguma dúvida?",
        "Oi! Como posso assistir?",
        "Olá! Precisa de ajuda?",
        "Oi! Tem algum problema?",
        "Olá! Como posso resolver?",
        "Oi! Precisa de orientação?",
        "Olá! Tem alguma questão?",
        "Oi! Como posso ser útil?",
        
        // Perguntas sobre problemas
        "Qual o problema?",
        "O que aconteceu?",
        "Qual a dificuldade?",
        "O que não está funcionando?",
        "Qual o erro?",
        "O que está dando errado?",
        "Qual a falha?",
        "O que está travado?",
        "Qual o bug?",
        "O que está com problema?",
        
        // Conversas sobre diagnóstico
        "Quando começou?",
        "Há quanto tempo?",
        "Desde quando?",
        "Quando você notou?",
        "Em que momento?",
        "Qual a frequência?",
        "Quantas vezes?",
        "Sempre acontece?",
        "É constante?",
        "É intermitente?",
        
        // Perguntas sobre contexto
        "O que você estava fazendo?",
        "Qual ação você executou?",
        "Que processo você seguiu?",
        "Qual passo você deu?",
        "O que você tentou?",
        "Qual método você usou?",
        "Que ferramenta você usou?",
        "Qual sistema você usou?",
        "Que aplicativo você usou?",
        "Qual plataforma você usou?",
        
        // Conversas sobre ambiente
        "Qual seu sistema operacional?",
        "Qual navegador você usa?",
        "Qual versão você tem?",
        "Qual dispositivo você usa?",
        "Qual modelo você tem?",
        "Qual configuração você tem?",
        "Qual memória você tem?",
        "Qual processador você tem?",
        "Qual conexão você usa?",
        "Qual velocidade você tem?",
        
        // Perguntas sobre tentativas
        "Você já tentou reiniciar?",
        "Você já tentou atualizar?",
        "Você já tentou reinstalar?",
        "Você já tentou limpar?",
        "Você já tentou resetar?",
        "Você já tentou recarregar?",
        "Você já tentou fechar?",
        "Você já tentou abrir?",
        "Você já tentou conectar?",
        "Você já tentou desconectar?",
        
        // Conversas sobre soluções
        "Vamos tentar isso!",
        "Teste esta solução!",
        "Experimente este método!",
        "Tente esta abordagem!",
        "Use esta alternativa!",
        "Aplique esta correção!",
        "Execute este comando!",
        "Siga este passo!",
        "Implemente esta solução!",
        "Adote esta medida!",
        
        // Perguntas sobre resultado
        "Funcionou?",
        "Resolveu?",
        "Melhorou?",
        "Corrigiu?",
        "Saiu do problema?",
        "Está funcionando?",
        "Está resolvido?",
        "Está melhor?",
        "Está correto?",
        "Está normal?",
        
        // Conversas sobre prevenção
        "Para evitar isso!",
        "Para prevenir problemas!",
        "Para manter funcionando!",
        "Para não acontecer novamente!",
        "Para garantir estabilidade!",
        "Para manter atualizado!",
        "Para evitar conflitos!",
        "Para manter seguro!",
        "Para garantir performance!",
        "Para manter otimizado!",
        
        // Perguntas finais
        "Mais alguma dúvida?",
        "Outro problema?",
        "Mais alguma questão?",
        "Outra dificuldade?",
        "Mais alguma coisa?",
        "Outro erro?",
        "Mais alguma pergunta?",
        "Outra falha?",
        "Mais alguma informação?",
        "Outro problema?",
        
        // Conversas finais
        "Foi um prazer ajudar!",
        "Obrigado pelo contato!",
        "Até a próxima!",
        "Foi ótimo resolver!",
        "Conversa muito boa!",
        "Obrigado pela paciência!",
        "Até logo!",
        "Foi interessante!",
        "Obrigado pela confiança!",
        "Até mais!"
    ],
    responses: [
        "Preciso de ajuda!",
        "Tenho um problema!",
        "Algo não está funcionando!",
        "Preciso de suporte!",
        "Tenho uma dúvida!",
        "Algo deu errado!",
        "Preciso resolver algo!",
        "Tenho uma questão!",
        "Algo está travado!",
        "Preciso de orientação!",
        "O problema é que não carrega!",
        "Aconteceu quando tentei abrir!",
        "A dificuldade é que trava!",
        "Não está funcionando o login!",
        "O erro é de conexão!",
        "Está dando erro 404!",
        "A falha é no sistema!",
        "Está travado na tela!",
        "O bug é no aplicativo!",
        "Está com problema de performance!",
        "Começou hoje de manhã!",
        "Há cerca de 2 horas!",
        "Desde ontem!",
        "Notei há pouco!",
        "No momento que abri!",
        "A frequência é constante!",
        "Acontece várias vezes!",
        "Sempre que tento usar!",
        "É constante mesmo!",
        "É intermitente!",
        "Estava tentando fazer login!",
        "Executei o comando de atualização!",
        "Segui o processo normal!",
        "Dei o passo de configuração!",
        "Tentei reiniciar!",
        "Usei o método padrão!",
        "Usei a ferramenta de diagnóstico!",
        "Usei o sistema de backup!",
        "Usei o aplicativo móvel!",
        "Usei a plataforma web!",
        "Uso Windows 11!",
        "Uso Chrome!",
        "Tenho a versão mais recente!",
        "Uso um notebook!",
        "Tenho um Dell!",
        "Tenho 16GB de RAM!",
        "Tenho Intel i7!",
        "Tenho SSD de 512GB!",
        "Uso Wi-Fi!",
        "Tenho 100MB!",
        "Já tentei reiniciar!",
        "Já tentei atualizar!",
        "Já tentei reinstalar!",
        "Já tentei limpar cache!",
        "Já tentei resetar!",
        "Já tentei recarregar!",
        "Já tentei fechar e abrir!",
        "Já tentei abrir novamente!",
        "Já tentei reconectar!",
        "Já tentei desconectar!",
        "Vou tentar!",
        "Vou testar!",
        "Vou experimentar!",
        "Vou tentar essa abordagem!",
        "Vou usar essa alternativa!",
        "Vou aplicar essa correção!",
        "Vou executar esse comando!",
        "Vou seguir esse passo!",
        "Vou implementar essa solução!",
        "Vou adotar essa medida!",
        "Funcionou perfeitamente!",
        "Resolveu completamente!",
        "Melhorou muito!",
        "Corrigiu o problema!",
        "Saiu do problema!",
        "Está funcionando normal!",
        "Está resolvido!",
        "Está muito melhor!",
        "Está correto agora!",
        "Está funcionando normal!",
        "Ótima dica!",
        "Vou seguir essas dicas!",
        "Vou manter atualizado!",
        "Vou evitar isso!",
        "Vou garantir estabilidade!",
        "Vou manter funcionando!",
        "Vou evitar conflitos!",
        "Vou manter seguro!",
        "Vou garantir performance!",
        "Vou manter otimizado!",
        "Não, obrigado!",
        "Está tudo resolvido!",
        "Não tenho mais dúvidas!",
        "Já resolvi tudo!",
        "Não preciso de mais nada!",
        "Está perfeito!",
        "Não tenho outras perguntas!",
        "Já esclareci tudo!",
        "Não tenho mais questões!",
        "Já tenho todas as informações!",
        "Foi ótimo mesmo!",
        "Obrigado pela ajuda!",
        "Até a próxima!",
        "Foi um prazer!",
        "Conversa excelente!",
        "Obrigado pela paciência!",
        "Até logo!",
        "Foi muito interessante!",
        "Obrigado pela solução!",
        "Até mais!"
    ]
};

// ========================================
// EXPORTAÇÃO DOS VASCOS
// ========================================
const CONVERSATION_BANKS = {
    business: BUSINESS_CONVERSATIONS,
    social: SOCIAL_CONVERSATIONS,
    customer: CUSTOMER_CONVERSATIONS,
    support: SUPPORT_CONVERSATIONS
};

// Função para obter configuração de conversa
function getConversationConfig(type) {
    return CONVERSATION_BANKS[type] || CONVERSATION_BANKS.social;
}

// Função para obter mensagem aleatória
function getRandomMessage(type) {
    const config = getConversationConfig(type);
    const randomIndex = Math.floor(Math.random() * config.messages.length);
    return config.messages[randomIndex];
}

// Função para obter resposta aleatória
function getRandomResponse(type) {
    const config = getConversationConfig(type);
    const randomIndex = Math.floor(Math.random() * config.responses.length);
    return config.responses[randomIndex];
}

// Função para obter intervalo aleatório
function getRandomInterval() {
    return Math.floor(Math.random() * (CONVERSATION_CONFIG.maxInterval - CONVERSATION_CONFIG.minInterval)) + CONVERSATION_CONFIG.minInterval;
}

// Exportar para uso global
if (typeof window !== 'undefined') {
    window.CONVERSATION_BANKS = CONVERSATION_BANKS;
    window.getConversationConfig = getConversationConfig;
    window.getRandomMessage = getRandomMessage;
    window.getRandomResponse = getRandomResponse;
    window.getRandomInterval = getRandomInterval;
    window.CONVERSATION_CONFIG = CONVERSATION_CONFIG;
}
